#!/usr/bin/with-contenv bash

JAVAMEM=${MAXMEM:-1024}

cd /opt/ubooquity || exit

s6-setuidgid alpine exec \
	java -Xmx"$JAVAMEM"m \
	-jar /opt/ubooquity/Ubooquity.jar \
	--headless \
	--host 0.0.0.0 \
	--libraryport 2202 \
	--adminport 2203 \
	--remoteadmin \
	--workdir /config

