#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/fonts

# copy config
# [[ ! -e /config/preferences.xml ]] && \
	    # cp /defaults/preferences.xml /config/preferences.xml

[[ ! -e /config/preferences.json ]] && \
	cp /defaults/preferences.json /config/preferences.json

# permissions
chown -R alpine:alpine \
	/config \
	/opt/ubooquity
